-- Generated by RPy — do not edit manually
local _RT = require(script.Parent.python_runtime)
local py_append = _RT.py_append
local py_len = _RT.py_len
local py_str = _RT.py_str
"RPy Example: NPC movement with patrol points."
local NPC = {}
NPC.__index = NPC

"Simple NPC that patrols between waypoints."
function NPC.new(name, speed)
	local self = setmetatable({}, NPC)
	self.name = name
	self.speed = speed
	self.health = 100
	self.waypoints = {}
	self.current_index = 0
	self.model = Instance.new("Model")
	self.model.Name = name
	self.model.Parent = workspace
	return self
end

function NPC:add_waypoint(position)
	"Add a patrol waypoint."
	py_append(self.waypoints, position)
end

function NPC:take_damage(amount)
	"Apply damage to this NPC."
	self.health = (self.health - amount)
	if (self.health <= 0) then
		self.health = 0
		print((py_str(self.name) .. " has been defeated!"))
	end
end

function NPC:is_alive()
	return (self.health > 0)
end

function NPC:get_next_waypoint()
	"Get the next patrol destination."
	if (py_len(self.waypoints) == 0) then
		return nil
	end
	local wp = self.waypoints[self.current_index + 1]
	self.current_index = ((self.current_index + 1) % py_len(self.waypoints))
	return wp
end


local guard = NPC("Guard", 16)
guard.add_waypoint(Vector3.new(0, 0, 0))
guard.add_waypoint(Vector3.new(50, 0, 0))
guard.add_waypoint(Vector3.new(50, 0, 50))
guard.add_waypoint(Vector3.new(0, 0, 50))
for step = 0, 7 do
	local wp = guard.get_next_waypoint()
	print((py_str(guard.name) .. " moving to waypoint " .. py_str(step)))
end