-- Generated by RPy — do not edit manually
local function test_try_except()
	local _ok, _err = pcall(function()
		local x = (1 / 0)
	end)
	if not _ok then
		local e = _err
		print("ValueError caught")
	elseif not _ok then
		local e = _err
		print("Other exception", e)
	end
	if _ok then
		print("No exceptions")
	end
	print("Finally block")
end

test_try_except()

return { test_try_except = test_try_except }