-- Generated by RPy — do not edit manually
local py_iter, py_set_add, py_set_difference, py_set_discard, py_set_intersection, py_set_new, py_set_union
function py_iter(iterable)
    local t = type(iterable)
    if t == "table" then
        if iterable._is_set then
            local f, s, var = pairs(iterable.items)
            return function(_, prev)
                local k = f(s, prev)
                if k ~= nil then return 0, k end
                return nil
            end, s, var
        end
        return ipairs(iterable)
    end
    return function() end
end
function py_set_add(s, item)
    if not s.items[item] then
        s.items[item] = true
        s._count = s._count + 1
    end
end
function py_set_difference(s1, s2)
    local s = py_set_new()
    for k in pairs(s1.items) do
        if not s2.items[k] then py_set_add(s, k) end
    end
    return s
end
function py_set_discard(s, item)
    if s.items[item] then
        s.items[item] = nil
        s._count = s._count - 1
    end
end
function py_set_intersection(s1, s2)
    local s = py_set_new()
    for k in pairs(s1.items) do
        if s2.items[k] then py_set_add(s, k) end
    end
    return s
end
function py_set_new(iterable)
    local s = { _is_set = true, items = {}, _count = 0 }
    if iterable then
        for _, v in py_iter(iterable) do
            if not s.items[v] then
                s.items[v] = true
                s._count = s._count + 1
            end
        end
    end
    return s
end
function py_set_union(s1, s2)
    local s = py_set_new()
    for k in pairs(s1.items) do py_set_add(s, k) end
    for k in pairs(s2.items) do py_set_add(s, k) end
    return s
end

local s1 = py_set_new({1, 2, 3})
local s2 = py_set_new({3, 4, 5})
py_set_add(s1, 10)
py_set_discard(s1, 1)
print("s1 intersection s2:", py_set_intersection(s1, s2))
print("s1 union s2:", py_set_union(s1, s2))
print("s1 difference s2:", py_set_difference(s1, s2))

return { s1 = s1, s2 = s2 }