-- Generated by RPy — do not edit manually
for i = 0, 4 do
	if (i == 3) then
		break
	end
	print("for no-orelse:", i)
end
local _break_0 = false
for i = 0, 2 do
	print("for orelse success:", i)
end
if not _break_0 then
	print("for orelse success hit!")
end
local _break_0 = false
for i = 0, 4 do
	if (i == 2) then
		_break_0 = true
		break
	end
	print("for orelse break:", i)
end
if not _break_0 then
	print("for orelse break hit! (should not print)")
end
local x = 0
local _break_0 = false
while (x < 3) do
	print("while orelse success:", x)
	x = x + 1
end
if not _break_0 then
	print("while orelse success hit!")
end
local y = 0
local _break_0 = false
while (y < 3) do
	if (y == 1) then
		_break_0 = true
		break
	end
	print("while orelse break:", y)
	y = y + 1
end
if not _break_0 then
	print("while orelse break hit! (should not print)")
end

return { i = i, x = x, y = y }