-- Generated by RPy — do not edit manually
local function py_iter(iterable)
    local t = type(iterable)
    if t == "table" then
        if iterable._is_set then
            local f, s, var = pairs(iterable.items)
            return function(_, prev)
                local k = f(s, prev)
                if k ~= nil then return 0, k end
                return nil
            end, s, var
        end
        return ipairs(iterable)
    end
    return function() end
end
local function py_slice(tbl, start, stop, step)
    local n = #tbl
    step = step or 1
    if start == nil then start = step > 0 and 0 or (n - 1)
    elseif start < 0 then start = math.max(0, n + start) end
    if stop == nil then stop = step > 0 and n or -1
    elseif stop < 0 then stop = math.max(0, n + stop) end
    local result = {}
    local i = start
    if step > 0 then
        while i < stop do
            table.insert(result, tbl[i + 1])
            i = i + step
        end
    elseif step < 0 then
        while i > stop do
            table.insert(result, tbl[i + 1])
            i = i + step
        end
    end
    return result
end

local numbers = {1, 2, 3, 4, 5}
local doubled = (function() local _r = {} for _, x in py_iter(numbers) do if (x > 2) then table.insert(_r, (x * 2)) end end return _r end)()
print(doubled)
local sliced = py_slice(numbers, 1, 4, 2)
print(sliced)
local squares = (function() local _r = {} for _, x in py_iter(numbers) do _r[x] = (x * x) end return _r end)()
print(squares)

return { doubled = doubled, numbers = numbers, sliced = sliced, squares = squares }