-- Generated by RPy — do not edit manually
local py_len
function py_len(x)
    local t = type(x)
    if t == "string" then
        return string.len(x)
    elseif t == "table" then
        if x._is_set then return x._count end
        return #x
    end
    error("py_len: unsupported type '" .. t .. "'", 2)
end

local function analyze(item)
	if (item == 1) then
		print("One")
	elseif (py_len(item) == 2) and true and (item[2] == 2) then
		local x = item[1]
		print("List ending in 2, start:", x)
	elseif (py_len(item) == 3) and (item[1] == 1) and true and (item[3] == 3) then
		local y = item[2]
		print("Middle:", y)
	elseif true then
		print("Other")
	end
end

analyze(1)
analyze({5, 2})
analyze({1, 10, 3})
analyze("Hello")

return { analyze = analyze }