-- Generated by RPy — do not edit manually
local _RT = require(script.Parent.python_runtime)
local py_append = _RT.py_append
local py_len = _RT.py_len
local py_str = _RT.py_str
local function create_brick(name, size)
	local part = Instance.new("Part")
	part.Name = name
	part.Size = size
	part.Parent = workspace
	return part
end

local bricks = {}
for i = 0, 4 do
	local b = create_brick(("Brick_" .. py_str(i)), (i * 2))
	py_append(bricks, b)
end
if (py_len(bricks) > 0) then
	print("Created bricks!")
end