-- Generated by RPy — do not edit manually
local plrs = game:GetService("Players")
local part = workspace:Raycast(Vector3.new(0, 0, 0), Vector3.new(0, (-10), 0))
local player = game.Players.LocalPlayer
local character = player.Character
_ = character.Humanoid:TakeDamage(10)
_ = workspace.Baseplate.Touched:Connect(function()
    return print("Baseplate touched")
end)