-- Generated by RPy — do not edit manually
local part = Instance.new("Part")
local function on_touch(hit)
    _ = print(("Touched by " .. tostring(hit.Name)))
end
_ = part.Touched:Connect(on_touch)
_ = part.Touched:Once(on_touch)
_ = part.Touched:Wait()