-- Generated by RPy — do not edit manually
local _RT = require(script.Parent.python_runtime)
local py_append = _RT.py_append
local py_bool = _RT.py_bool
local py_len = _RT.py_len
local py_str = _RT.py_str
"RPy Example: Enemy class with inheritance."
local Entity = {}
Entity.__index = Entity

"Base class for all game entities."
function Entity.new(name, health)
	local self = setmetatable({}, Entity)
	self.name = name
	self.health = health
	self.max_health = health
	self.alive = true
	return self
end

function Entity:take_damage(amount)
	self.health = (self.health - amount)
	if (self.health <= 0) then
		self.health = 0
		self.alive = false
		self.on_death()
	end
end

function Entity:heal(amount)
	self.health = (self.health + amount)
	if (self.health > self.max_health) then
		self.health = self.max_health
	end
end

function Entity:on_death()
	print((py_str(self.name) .. " has died!"))
end


local Enemy = setmetatable({}, {__index = Entity})
Enemy.__index = Enemy

"An enemy entity with attack power and loot."
function Enemy.new(name, health, damage)
	local self = setmetatable({}, Enemy)
	self.name = name
	self.health = health
	self.max_health = health
	self.alive = true
	self.damage = damage
	self.loot = {}
	return self
end

function Enemy:add_loot(item)
	py_append(self.loot, item)
end

function Enemy:attack(target)
	if py_bool(self.alive) then
		target.take_damage(self.damage)
		print((py_str(self.name) .. " attacks " .. py_str(target.name) .. " for " .. py_str(self.damage) .. " damage!"))
	end
end

function Enemy:drop_loot()
	if (py_len(self.loot) > 0) then
		print((py_str(self.name) .. " drops:"))
		for _, item in ipairs(self.loot) do
			print(("  - " .. py_str(item)))
		end
	end
	return self.loot
end


local zombie = Enemy("Zombie", 50, 10)
zombie.add_loot("Rotten Flesh")
zombie.add_loot("Gold Coin")
local skeleton = Enemy("Skeleton", 30, 15)
skeleton.add_loot("Bone")
skeleton.add_loot("Arrow")
local hero = Entity("Hero", 100)
zombie.attack(hero)
skeleton.attack(hero)
print(("Hero health: " .. py_str(hero.health) .. "/" .. py_str(hero.max_health)))
zombie.take_damage(50)
local items = zombie.drop_loot()