-- Generated by RPy — do not edit manually
local _RT = require(script.Parent.python_runtime)
local py_len = _RT.py_len
local py_str = _RT.py_str
"RPy Example: Iterating over players."
local function greet_players()
	"Print a greeting for each player in the server."
	local players_service = game.GetService("Players")
	local player_list = players_service.GetPlayers()
	for i = 0, (py_len(player_list) - 1) do
		local player = player_list[i + 1]
		print(("Welcome, " .. py_str(player.Name) .. "!"))
	end
	print(("Total players: " .. py_str(py_len(player_list))))
end

greet_players()