-- Generated by RPy — do not edit manually
local _RT = require(script.Parent.python_runtime)
local py_str = _RT.py_str
"RPy Example: Spawning parts in the workspace."
local function spawn_part(position, color)
	"Create a new Part at the given position with a color."
	local part = Instance.new("Part")
	part.Size = Vector3.new(4, 1, 2)
	part.Position = position
	part.BrickColor = color
	part.Anchored = true
	part.Parent = workspace
	return part
end

for i = 0, 9 do
	local pos = Vector3.new((i * 5), 10, 0)
	spawn_part(pos, "Bright blue")
	print(("Spawned part " .. py_str(i)))
end