"""
transpiler/package_manager.py — Stage 18: RPy Package Management.
"""

import os
import json
import shutil
import subprocess
from pathlib import Path
from typing import Dict, List, Optional

class PackageManager:
    def __init__(self, project_root: str = "."):
        self.project_root = Path(project_root)
        self.packages_dir = self.project_root / "rpy_packages"
        self.config_path = self.project_root / "rpy.json"

    def load_config(self) -> dict:
        if not self.config_path.exists():
            return {}
        try:
            with open(self.config_path, "r", encoding="utf-8") as f:
                return json.load(f)
        except Exception:
            return {}

    def save_config(self, config: dict):
        with open(self.config_path, "w", encoding="utf-8") as f:
            json.dump(config, f, indent=2)

    def install(self):
        """Main entry point for 'rpy install'."""
        config = self.load_config()
        dependencies = config.get("dependencies", {})
        
        if not dependencies:
            print("No dependencies found in rpy.json.")
            return

        print(f"Installing {len(dependencies)} dependencies...")
        
        if not self.packages_dir.exists():
            self.packages_dir.mkdir(parents=True)

        # For Stage 18, we will focus on Wally integration
        self._sync_wally(dependencies)
        
        # After Luau packages are installed, we generate Python stubs
        self._generate_stubs()

    def _sync_wally(self, dependencies: Dict[str, str]):
        """Generates wally.toml and runs wally install if possible."""
        wally_config = {
            "package": {
                "name": "rpy/project",
                "description": "Auto-generated by RPy",
                "version": "0.1.0",
                "license": "MIT",
                "authors": ["RPy"]
            },
            "dependencies": dependencies
        }
        
        # Convert JSON-like dict to TOML manually or use a lib
        # For simplicity in this stage, we'll write a simple wally.toml
        wally_path = self.project_root / "wally.toml"
        with open(wally_path, "w", encoding="utf-8") as f:
            f.write("[package]\n")
            f.write(f'name = "{wally_config["package"]["name"]}"\n')
            f.write(f'version = "{wally_config["package"]["version"]}"\n')
            f.write(f'registry = "https://github.com/UpliftGames/wally-index"\n')
            f.write('realm = "shared"\n\n')
            f.write("[dependencies]\n")
            for name, version in dependencies.items():
                f.write(f'{name} = "{version}"\n')
        
        print(f"Generated {wally_path}")
        
        # Run wally install if available
        try:
            subprocess.run(["wally", "install"], cwd=str(self.project_root), check=True)
            print("Wally dependencies installed successfully.")
        except FileNotFoundError:
            print("Warning: 'wally' command not found. Please install Wally to fetch Luau packages.")
        except subprocess.CalledProcessError as e:
            print(f"Error: 'wally install' failed: {e}")

    def _generate_stubs(self):
        """Scans rpy_packages and creates Python stubs for the analyzer."""
        # This will be implemented in the next sub-step
        print("Stub generation: Scanning Packages/ directory...")
        packages_folder = self.project_root / "Packages"
        if not packages_folder.exists():
            return

        for entry in packages_folder.iterdir():
            if entry.is_dir():
                # For each package, create a .py file so RPy can 'import' it
                self._create_stub_for_package(entry)

    def _create_stub_for_package(self, package_path: Path):
        """Creates a minimal Python file representing the Luau package's API."""
        package_name = package_path.name
        stub_path = self.packages_dir / f"{package_name}.py"
        
        # Basic stub: everything is an 'Any' object or we could try simple parsing
        content = f'"""Auto-generated stub for Luau package {package_name}"""\n'
        content += "from typing import Any\n\n"
        content += f"class {package_name}:\n"
        content += "    def __getattr__(self, name: str) -> Any: ...\n\n"
        content += f"{package_name} = {package_name}()\n"
        
        with open(stub_path, "w", encoding="utf-8") as f:
            f.write(content)
        print(f"  Generated stub: {stub_path}")
